//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  By considering the terms in the Fibonacci sequence whose values do not exceed 1000, find the sum of the even-valued terms.


using System.Runtime.InteropServices;

List<int> fibonacciList = new List<int>();
List<int> evenList = new List<int>();
int firstTerm = 0, secondTerm = 1, termFibonacci, evenSum;

termFibonacci = firstTerm + secondTerm;
fibonacciList.Add(firstTerm);
fibonacciList.Add(secondTerm);
fibonacciList.Add(termFibonacci);

for (int i = 1; termFibonacci < 1000; i++)
    {
        firstTerm = secondTerm;
        secondTerm = termFibonacci;
        termFibonacci = firstTerm + secondTerm;
          if (termFibonacci < 1000)
          {
        fibonacciList.Add(termFibonacci);
          }
          if (termFibonacci % 2 == 0 && termFibonacci < 1000)
          {        
        evenList.Add(termFibonacci);      
          }
        
    }

Console.WriteLine("The Fibonnaci List is: " + string.Join(",", fibonacciList));
Console.WriteLine("The Fibonnaci even terms below the value 1000 are : " + string.Join( ",", evenList));
evenSum = evenList.Sum(x => Convert.ToInt32(x));
Console.WriteLine($"The sum of even Fibonacci terms is {evenSum}");
//fibonacciList.ForEach(Console.WriteLine);
//Console.WriteLine("  {0}", String.Join(" ", fibonacciList));
//evenList.ForEach(Console.WriteLine);
